SELECT id, name, options FROM item 
WHERE options LIKE '%"id":127%' 
   OR options LIKE '%"id":128%' 
   OR options LIKE '%"id":129%' 
   OR options LIKE '%"id":130%' 
   OR options LIKE '%"id":131%' 
   OR options LIKE '%"id":132%' 
   OR options LIKE '%"id":133%' 
   OR options LIKE '%"id":134%' 
   OR options LIKE '%"id":135%' 
   OR options LIKE '%"id": 127%' 
   OR options LIKE '%"id": 128%' 
   OR options LIKE '%"id": 129%' 
   OR options LIKE '%"id": 130%' 
   OR options LIKE '%"id": 131%' 
   OR options LIKE '%"id": 132%' 
   OR options LIKE '%"id": 133%' 
   OR options LIKE '%"id": 134%' 
   OR options LIKE '%"id": 135%';
